GET http://localhost:3003/api/notes HTTP/1.1
###


GET http://localhost:3003/api/notes/622f052222b66d900550467


###

POST http://localhost:3003/api/notes
Content-Type: application/json
    
{
    "importance": "hhhhh"
}

###

POST http://localhost:3003/api/notes
Content-Type: application/json
    
{
     "content": "in love with this",
    "importance":true
}

###

DELETE http://localhost:3003/api/notes/622f037e2b3d2dc42bce6e1

###

PUT http://localhost:3003/api/notes/622f213a1fab767e72885999
Content-Type: application/json

{

    "important": false
}
